program enduro;

uses
  Vcl.Forms,
  Unit1 in 'Unit1.pas' {Principal},
  LoginForm in 'LoginForm.pas' {Login},
  DataModule in 'DataModule.pas' {ConnectionModule: TDataModule},
  F_EEMessage in 'F_EEMessage.pas' {F_EE_Message},
  Entidades in 'Entidades.pas',
  ValidationHelper in 'ValidationHelper.pas',
  BindingHelperUnit in 'BindingHelperUnit.pas',
  AbstractCRUD in 'AbstractCRUD.pas' {AbstractCRUDFrame: TFrame},
  AbstractEditor in 'AbstractEditor.pas' {AbstractEdit},
  EditMemosEditor in 'EditMemosEditor.pas' {EditMemos},
  UserCRUDUnit in 'UserCRUDUnit.pas' {UserCRUD: TFrame},
  UserEditorUnit in 'UserEditorUnit.pas' {UserEditor},
  BussinessDataSubsystemFacade in 'BussinessDataSubsystemFacade.pas',
  EncodingHelper in 'EncodingHelper.pas',
  LoggedUserSingleton in 'LoggedUserSingleton.pas',
  PilotCRUDUnit in 'PilotCRUDUnit.pas' {PilotCRUD: TFrame},
  PilotEditorUnit in 'PilotEditorUnit.pas' {PilotEditor},
  EventCRUDUnit in 'EventCRUDUnit.pas' {EventCRUD: TFrame},
  EventoEditorUnit in 'EventoEditorUnit.pas' {EventEditor},
  InscripcionCRUD in 'InscripcionCRUD.pas' {InscripcionesCRUD: TFrame},
  PuntuacionCRUDUnit in 'PuntuacionCRUDUnit.pas' {PuntuacionCRUD: TFrame},
  ConfigurationEditorFrame in 'ConfigurationEditorFrame.pas' {ConfigurationFrame: TFrame},
  ConfigureFilesUtilities in 'ConfigureFilesUtilities.pas',
  CategoriaCrudUnit in 'CategoriaCrudUnit.pas' {CategoriaCRUD: TFrame},
  CategoriaEdit in 'CategoriaEdit.pas' {CategoriaEditor},
  HandicupCRUDUnit in 'HandicupCRUDUnit.pas' {HandicupCRUD: TFrame},
  HandicupEditUnit in 'HandicupEditUnit.pas' {HandicupEditor},
  MotoCRUDUnit in 'MotoCRUDUnit.pas' {MotoCRUD: TFrame},
  MotoEditorUnit in 'MotoEditorUnit.pas' {MotoEditor},
  PilotEditorInnerUnit in 'PilotEditorInnerUnit.pas' {PilotInnerEditor},
  GrillaTiempoEspera in 'GrillaTiempoEspera.pas' {FGrillaTiempoEspera},
  FormularioTiempoEspera in 'FormularioTiempoEspera.pas' {AddPilotToWaitingGrid},
  ReportPuestoEvento in 'ReportPuestoEvento.pas' {ReportePuestoEvento},
  F_CustReport in 'F_CustReport.pas' {CustPreview},
  ReportTotalPuestoEvento in 'ReportTotalPuestoEvento.pas' {ReporteTotalPuestoEvento},
  CampeonatoCRUDUnit in 'CampeonatoCRUDUnit.pas' {CampeonatoCRUD: TFrame},
  CampeonatoEditorUnit in 'CampeonatoEditorUnit.pas' {CampeonatoEditor},
  ReporteMotos in 'ReporteMotos.pas' {ReportMotos},
  ReportePuntuacionEvento in 'ReportePuntuacionEvento.pas' {ReportPuntuacionEvento},
  MotoEditorInnerUnit in 'MotoEditorInnerUnit.pas' {MotoEditorInner},
  TomaTiemposUnit in 'TomaTiemposUnit.pas' {TomaTiempos},
  GrillaPartidaUnit in 'GrillaPartidaUnit.pas' {GrillaPartida},
  CambiarEstadoPilotoGrillaUnit in 'CambiarEstadoPilotoGrillaUnit.pas' {CambiarEstadoPilotoGrilla},
  Demopreview in 'Demopreview.pas' {FormPreview},
  AddTomaTiempo in 'AddTomaTiempo.pas' {AddTomaTiempoForm},
  GrillaTomaTiempo in 'GrillaTomaTiempo.pas' {GrillaTomaTiempoForm},
  RecargoTomaTiempoEventoUnit in 'RecargoTomaTiempoEventoUnit.pas' {RecargoTomaTiempoEvento},
  TomaTiemposEditUnit in 'TomaTiemposEditUnit.pas' {TomaTiemposEdit},
  ReconocimientoUnit in 'ReconocimientoUnit.pas' {Reconocimiento},
  GrillaReconocimiento in 'GrillaReconocimiento.pas' {GrillaReconocimientoForm},
  ContactoCRUDUnit in 'ContactoCRUDUnit.pas' {ContactCRUD: TFrame},
  ContactoEditorUnit in 'ContactoEditorUnit.pas' {ContactEdit},
  GrillaTomaTiempoMultiCat in 'GrillaTomaTiempoMultiCat.pas' {GrillaTomaTiempoMultiCatForm},
  ConsultaDatosPilotoUnit in 'ConsultaDatosPilotoUnit.pas' {ConsultaDatosPiloto},
  GrillaReconocimientoMulti in 'GrillaReconocimientoMulti.pas' {GrillaReconocimientoMultiForm},
  AgrupacionReconocimiento in 'AgrupacionReconocimiento.pas' {AgrupacionReconocimientoForm},
  EditAgrupacionTomaTiempos in 'EditAgrupacionTomaTiempos.pas' {EdicionAgrupacion},
  GrillaAgrupacionTomasMultiCat in 'GrillaAgrupacionTomasMultiCat.pas' {GrillaAgrupacionMultiCatForm},
  NumeracionDisponibleEdit in 'NumeracionDisponibleEdit.pas' {FormNumeracionDisponible},
  NaveganteEdit in 'NaveganteEdit.pas' {NaveganteEditor},
  GrillaAbastecimiento in 'GrillaAbastecimiento.pas' {FGrillaAbastecimiento},
  AgregarTomaTiempoAbastecimiento in 'AgregarTomaTiempoAbastecimiento.pas' {AddTomaTiempoAbastecimiento},
  ImportarAbastecimientoEnTomaTiempo in 'ImportarAbastecimientoEnTomaTiempo.pas' {ImportarTomaTiempoAbastecimiento},
  GrillaAdministracionAbastecimiento in 'GrillaAdministracionAbastecimiento.pas' {TAdminGillaAbastecimiento},
  AgregarTomaTiempoAbastecimientoWithTime in 'AgregarTomaTiempoAbastecimientoWithTime.pas' {AddTomaTiempoAbastecimientoWithTime},
  GrillaTomaTiempoMultiCatEPU in 'GrillaTomaTiempoMultiCatEPU.pas' {GrillaTomaTiempoMultiCatEPUForm},
  PuntosCRUDUnit in 'PuntosCRUDUnit.pas' {TPuntosCRUD: TFrame},
  PuntosEditUnit in 'PuntosEditUnit.pas' {PuntosEditor},
  AddTomaTiempoGrilla in 'AddTomaTiempoGrilla.pas' {TAddTomaTiempoGridForm},
  Utomatiempoio in 'Utomatiempoio.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TConnectionModule, ConnectionModule);
  Application.CreateForm(TPrincipal, Principal);
  Application.Run;
end.
